export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const GROUPS_ROUTE = '/'
export const PLAYLIST_ROUTE = '/playlist'
export const GROUP_ROUTE = '/group'
